version: 2
 
sources:
 
  - name: snapshot
    database: Capstone
    schema: bronze
 
    tables:
      - name: snapshot_customers
      - name: snapshot_campaign
      - name: snapshot_employee
      - name: snapshot_products
      - name: snapshot_store
      - name: snapshot_supplier